//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carshering
{
    using System;
    using System.Collections.Generic;
    
    public partial class payment
    {
        public int id { get; set; }
        public System.DateTime data { get; set; }
        public int number_of_rental_days { get; set; }
        public int id_user { get; set; }
        public int tariff_id { get; set; }
    
        public virtual tariffs tariffs { get; set; }
        public virtual users users { get; set; }
    }
}
